name: Build Android APK
on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest

      - name: ⚙️ Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 🛠 Prebuild & Build APK
        run: |
          npx expo prebuild
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: 📤 Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zid-app-apk
          path: android/app/build/outputs/apk/release/*.apk
