name: Build Android APK
on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  EXPO_PUBLIC_APPWRITE_ENDPOINT: ${{ secrets.EXPO_PUBLIC_APPWRITE_ENDPOINT }}
  EXPO_PUBLIC_APPWRITE_PROJECT_ID: ${{ secrets.EXPO_PUBLIC_APPWRITE_PROJECT_ID }}
  EXPO_PUBLIC_DATABASE_ID: ${{ secrets.EXPO_PUBLIC_DATABASE_ID }}
  EXPO_PUBLIC_GROQ_API_KEY: ${{ secrets.EXPO_PUBLIC_GROQ_API_KEY }}
  EXPO_PUBLIC_IMAGEKIT_ENDPOINT: ${{ secrets.EXPO_PUBLIC_IMAGEKIT_ENDPOINT }}
  EXPO_PUBLIC_IMAGEKIT_PUBLIC_KEY: ${{ secrets.EXPO_PUBLIC_IMAGEKIT_PUBLIC_KEY }}
  EXPO_PUBLIC_IMAGEKIT_PRIVATE_KEY: ${{ secrets.EXPO_PUBLIC_IMAGEKIT_PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: 📦 Install dependencies
        run: |
          npm install --legacy-peer-deps

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ⚙️ Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 🛠 Prebuild & Build APK (Debug Mode)
        run: |
          npx expo prebuild
          # توليد الـ Keystore عشان الـ Build ما يرفضش
          cd android/app
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
          cd ..
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: 📤 Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Zid-Debug-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
