name: Build Android APK
on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-cache: true

      - name: 🛠 Fix Cache Permissions
        run: git config --global --add safe.directory /home/runner/work/Zid/Zid

      - name: 🚀 Build Android APK
        run: |
          npx expo prebuild
          # ملاحظة: إذا كنت تستخدم EAS Build، استخدم الأمر التالي:
          # eas build --platform android --profile preview --local
        env:
          NODE_ENV: production

      - name: 📤 Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zid-app-apk
          path: android/app/build/outputs/apk/release/*.apk
